"""
Portas: contratos que a camada de aplicação espera da infraestrutura.
Os casos de uso dependem só destas interfaces; as implementações concretas (SQLite, Word,
Tesseract, SMTP...) ficam em folha_ponto.infraestrutura e são injetadas na raiz de composição.
"""
from typing import Callable, Iterable, Protocol

from ..dominio.entidades import (
    ConfiguracaoEmail, EventoOperacao, FolhaArquivada, ItemOperacao, Operacao, RegistroEnvio, Servidor,
)

# progresso(i, total, texto) — usado para barras de progresso em tarefas longas
Progresso = Callable[[int, int, str], None]


def sem_progresso(_i, _total, _texto=""):
    pass


# ------------------------------ persistência ------------------------------

class RepositorioServidores(Protocol):
    def listar(self, busca: str = "") -> list[Servidor]: ...
    def obter(self, servidor_id: int) -> Servidor | None: ...
    def contar(self) -> int: ...
    def salvar(self, servidor: Servidor) -> None: ...                    # MatriculaDuplicada se conflitar
    def importar(self, dados: dict) -> tuple[int, bool]: ...             # upsert por matrícula -> (id, novo?)


class RepositorioFolhas(Protocol):
    def registrar_gerada(self, servidor_id: int, competencia: str, docx: str, pdf: str | None) -> None: ...
    def digitalizada_por_hash(self, hash_arquivo: str) -> dict | None: ...
    def registrar_digitalizada(self, caminho: str, servidor_id: int | None, competencia: str, status: str,
                               texto: str, hash_arquivo: str, metodo: str) -> int: ...
    def vincular_digitalizada(self, doc_id: int, servidor_id: int, competencia: str, status: str) -> None: ...
    def listar_arquivadas(self, termo: str = "", competencia: str = "") -> list[FolhaArquivada]: ...
    def competencias(self) -> list[str]: ...


class RepositorioOperacoes(Protocol):
    def criar(self, operacao: Operacao) -> int: ...
    def atualizar(self, op_id: int, **campos) -> None: ...
    def obter(self, op_id: int) -> Operacao | None: ...
    def listar(self) -> list[Operacao]: ...
    def registrar_evento(self, op_id: int, momento: str, descricao: str) -> None: ...
    def eventos(self, op_id: int) -> list[EventoOperacao]: ...
    def salvar_itens(self, op_id: int, itens: Iterable[ItemOperacao]) -> None: ...
    def itens(self, op_id: int) -> list[ItemOperacao]: ...


class RepositorioEnvios(Protocol):
    def registrar(self, servidor_id: int, competencia: str, destinatario: str, status: str, detalhes: str,
                  anexo: str | None, operacao_id: int | None) -> None: ...
    def listar(self) -> list[RegistroEnvio]: ...


class RepositorioConfiguracoes(Protocol):
    def obter(self, chave: str, padrao: str = "") -> str: ...
    def definir(self, chave: str, valor: str) -> None: ...


# ------------------------------ serviços externos ------------------------------

class LeitorPlanilha(Protocol):
    def ler(self, caminho: str) -> tuple[list[dict], list[str]]: ...   # (registros, linhas ignoradas); PlanilhaInvalida
    def contar(self, caminho: str) -> int: ...


class GeradorFolhas(Protocol):
    def gerar_lote(self, servidores: list[Servidor], competencia: str, progresso: Progresso
                   ) -> tuple[dict[int, tuple[str, str | None]], list[str]]: ...
    # -> ({servidor_id: (caminho_docx, caminho_pdf ou None)}, erros)


class LeitorFolhas(Protocol):
    def texto_direto(self, caminho: str) -> str: ...
    def texto_ocr(self, caminho: str) -> str: ...
    def ocr_disponivel(self) -> bool: ...


class Enviador(Protocol):
    def __enter__(self) -> "Enviador": ...
    def __exit__(self, *exc) -> None: ...
    def enviar(self, destino: str, assunto: str, corpo: str, anexo: str | None) -> tuple[bool, str]: ...


class ServicoEmail(Protocol):
    def abrir(self, config: ConfiguracaoEmail) -> Enviador: ...
    def testar(self, config: ConfiguracaoEmail) -> tuple[bool, str]: ...


class GeradorRelatorio(Protocol):
    def gerar(self, operacao: Operacao, itens: list[ItemOperacao], eventos: list[EventoOperacao],
              gerado_em: str, destino: str) -> str: ...


class Armazenamento(Protocol):
    pasta_dados: str
    pasta_app: str
    pasta_relatorios: str
    modelo_folha: str
    modelo_planilha: str
    planilha_base: str

    def pasta_geradas(self, competencia: str) -> str: ...
    def arquivar_digitalizada(self, origem: str, competencia: str) -> str: ...
    def guardar_planilha_base(self, origem: str) -> None: ...
    def hash(self, caminho: str | None) -> str: ...
    def existe(self, caminho: str | None) -> bool: ...


class Ambiente(Protocol):
    def agora(self) -> str: ...        # "AAAA-MM-DD HH:MM:SS", horário local
    def usuario(self) -> str: ...
    def computador(self) -> str: ...
